const cardData = [
  {
    image: process.env.PUBLIC_URL + "/MovieReviewer.png",
    title: "Movie Reviewer",
    text: `For more information click the button below.`,
    Url: "https://github.com/Zim40/movieReviewer",
    deployedUrl: "https://secret-eyrie-67487-977068a16355.herokuapp.com/",
    technology: ["Javascript", "TailwindCss", "MongoDB", "Mongoose", "React", "JWT", "Bcrypt", "Express", "Third Party Api's"],
    completionStatus: false,
  },
  {
    image: process.env.PUBLIC_URL + "/FinanceApp.png",
    title: "Finance App",
    text: `For more information click the button below.`,
    Url: "https://github.com/benenhuntley7/finance-app",
    deployedUrl: "https://finance-app-orpin.vercel.app/",
    technology: ["TypeScript", "TailwindCss", "Postgres", "DrizzleORM", "NextJs"],
    completionStatus: false,
  },
  {
    image: process.env.PUBLIC_URL + "/FetchEvent.png",
    title: "Fetch Event",
    text: `For more information click the button below.`,
    Url: "https://github.com/Zim40/FetchEvent",
    deployedUrl: "https://lilyhargreaves.github.io/chilly-mandrills-project-one/",
    technology: ["JavaScript", "HTML", "CSS", "TicketMasterAPI", "REST", "Express"],
    completionStatus: true,
  },
  {
    image: process.env.PUBLIC_URL + "/Screenshot.png",
    title: "RuralTech: Admin Inventory",
    text: "For more information click the button below. ",
    Url: "https://github.com/Zim40/RuralTech-Ecommerce-",
    deployedUrl: "",
    technology: ["JavaScript", "HTML", "CSS", "React", "REST", "MongoDB", "Express", "Apollo-Server", "Bcrypt", "JWT", "Mongoose", "GraphQL"],
    completionStatus: true,
  },
  {
    image: process.env.PUBLIC_URL + "/wordleApp.png",
    title: "Wordle Replica",
    text: "For more information click the button below. ",
    Url: "https://github.com/Zim40/Wordle-Replica",
    deployedUrl: "https://zim40.github.io/Wordle-Replica/",
    technology: ["JavaScript", "HTML", "CSS", "React"],
    completionStatus: false,
  },
];
export default cardData;
